##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [3]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([50,60,70,80])
print(a+b)
print(a-b)
print(a*b)
print(a//b)




[ 60  80 100 120]
[-40 -40 -40 -40]
[ 500 1200 2100 3200]
[0 0 0 0]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [5]:
a=np.array([1,2,3,4])
print(a*2)

[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [8]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr*5)

[[ 5 10 15]
 [20 25 30]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [11]:
arr=np.array([4,15,16,67,43])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))


145
29.0
4
67
22.93468988235943
526.0


You can also do the axis based operations row-Wise and Colum-wise

In [15]:
data=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(np.sum(data))

45


In [19]:
print(np.sum(data,axis=1))
print(np.sum(data,axis=0))

[ 6 15 24]
[12 15 18]
